name = "ntut-app-qr"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[kv_namespaces]]
binding = "QR_SESSIONS"
id = "QR_SESSIONS_ID" # This is a placeholder for local dev
preview_id = "QR_SESSIONS_PREVIEW_ID"
